version: "3.9"
services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  api:
    build: .
    ports:
      - "8081:8081"
    volumes:
      - ./src:/code
    command: uvicorn app:main --reload --workers 1 --host 0.0.0.0 --port 8081
    depends_on:
      - db
    restart: always
  redis:
    image: "redis:alpine"